spring:
  application:
    name: nacos-consumer-ribbon
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

server:
  port: 9093

management:
  endpoints:
    web:
      exposure:
        include: "*"

ribbon:
  MaxAutoRetries: 2  #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试
  MaxAutoRetriesNextServer: 3  #切换实例的重试次数
  OkToRetryOnAllOperations: false  #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
  ConnectTimeout: 5000 #请求连接的超时时间
  ReadTimeout: 6000  #请求处理的超时时间
  #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #配置负载均衡算法-我这里使用的是自定义的Ribbon的负载均衡算法，默认
  #NFLoadBalancerRuleClassName: NacosClusterAwareWeightedRuleConfiguration #配置负载均衡算法-我这里使用的是自定义的Ribbon的负载均衡算法

